### ISSUE TITLE
Non-Existant Template Being Recorded

### ISSUE THREAD

**Issue by amorkan** [FriendsOfShopware/FroshViewSnapshots#10]
## Actual behaviour

When replaying a snapshot, when accessing a custom POST action that doesn't render a template but simply redirects to the next step in a process I get the following error:

Unable to load template snippet 'frontend/loyalty/webaccountpost.tpl|frontend/listing/listing_ajax.tpl|frontend/listing/listing_ajax.tpl|frontend/plugins/seo/index.tpl' in engine/Library/Smarty/sysplugins/smarty_internal_templatebase.php on line 127 

It's recording a template against this action when it should not.

## Expected behaviour

The custom POST action gets called with the variables in the params field, and I get redirected to the next page/step in the snapshot.

## Environment

SW 5.6.5
Ubuntu
PHP 7.2
Apache 2.4

## Steps to reproduce

1. Write a custom controller with an action that does accepts a POST and redirects to another action
2. Record going through the steps in this custom controller
3. Replay the steps

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshViewSnapshots/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin

**Comment by dneustadt** [comment]
Thanks for reporting the issue.
with the latest update redirects identified by the response code won't be recorded at all now. Since the request following the redirect was being recorded already this shouldn't have any consequences other than avoiding creating unusable records. The disadvantage of this change might be, that one might not be able to distinguish the origin of a request anymore, with the request issuing the redirect not being recorded anymore. Since this plugin is not meant to provide some sort of user tracking, I feel like it's ok to not record these steps. Anyway, this change should allow you to use the next/previous step functions without receiving the mentioned exception.

**Comment by amorkan** [comment]
Hi David,

Thanks for the quick update.

While this change fixes the error, it means that form submission no longer can be replicated as the plugin no longer visits the URL for the form action (with the recorded parameters). I guess ideally the step would be recorded as before, but if it's a redirect then no template is recorded?

In general, I'm trying to use this plugin to replicate errors on our sites that are hard to replicate.  I get an error email into my account and I'm trying to understand how it happened. I've customised it locally to record every session based on a configuration setting. (If this is useful I can add it as a PR). For this debugging to work, every step, including form submissions need to be replicated. Maybe this is out of scope for the plugin.

Things that would help me:

1. Ability to search in the backend by Session ID (Error Emails seem to be missing the Session ID at the moment but I think this might be a bug in Shopware) I looked into adding the search toolbar but my ExtJs isn't good enough yet!
2. A column added to the database table for the timestamp and the ability to search by timestamp in the backend (in the case where Session data isn't available, it would be useful to be able to narrow down and identify the session that generated the error).
3. A new session is being created once the customer logs in. I think this is a Shopware issue that I will look into.

I appreciate this is an open source project and happy to provide PRs where possible - I mainly just want to run this approach by you first.

thanks,

Alan.

**Comment by dneustadt** [comment]
Hi Alan,

that's certainly a very interesting use case. I only ever thought about this plugin as a supportive tool for frontend development. There's a problem with what you're trying to achieve here though. This plugin merely takes whatever is passed to the view and stores it in the database. When you recreate a snapshot all you get is a replica of the view so to speak. So no code that was responsible for creating the original view is being executed again. The way I see it, this makes the plugin completely unsuitable for debugging since, well, there isn't anything being executed that could be debugged, at least server-side that is. A series of snapshots is just a bunch of replica views written in the order they were requested. We would have to recreate the actual call of the controller action, to make this work for debugging.

**Comment by amorkan** [comment]
Given the controller name, action and params are already set in `loadAction()` setting the dispatched flag to false on the request makes the code call the original action... I suspect if we assigned the template variables for the Javascript in a subscriber instead, that it all might (more or less) work. Leave it with me and I'll see how I get on and submit a PR if I get something I'm happy with.
